version: '3.9'

services:
  db:
    image: postgres:16
    container_name: movies-lib-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    build:
      context: ./be
    container_name: movies-be
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "3000:3000"


  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: movies-fe
    restart: unless-stopped
    ports:
      - "5173:80" 
    depends_on:
      - be

volumes:
  pgdata: