version: '3.9'

services:
  db:
    image: postgres:16
    container_name: movies-lib-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  be:
    build:
      context: ./be
    container_name: movies-be
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/movies
    ports:
      - "3000:3000"

volumes:
  pgdata: